{% set name = "AGAT" %}
{% set version = "0.7.0" %}
{% set sha256 = "454714c423e75f6d4b03ecf1ddf89beabd74167b9686cfbf7de62467c205c1b0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/NBISweden/AGAT/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:

  host:
    - perl >=5.22,<6.0
    - perl-bioperl-core ==1.007002
    - perl-clone
    - perl-extutils-makemaker
    - perl-file-sharedir-install
    - perl-file-share 
    - perl-graph
    - perl-json
    - perl-lwp-simple
    - perl-moose
    - perl-sort-naturally
    - perl-statistics-r
    - perl-term-progressbar
    - libdb

  run:
    - perl >=5.22,<6.0
    - perl-bioperl-core ==1.007002
    - perl-file-sharedir-install
    - perl-file-share
    - perl-clone
    - perl-graph
    - perl-lwp-simple
    - perl-moose
    - perl-statistics-r
    - perl-json
    - perl-sort-naturally
    - perl-term-progressbar
    - libdb
test:
  commands:
    - agat_convert_sp_gxf2gxf.pl -h

about:
  home: https://github.com/NBISweden/AGAT
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Another Gff Analysis Toolkit (AGAT). Suite of tools to handle gene annotations in any GTF/GFF format.
  dev_url: https://github.com/NBISweden/AGAT

extra:
  recipe-maintainers:
    - juke34
