{% set name = "mikado" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Mikado-{{ version }}.tar.gz
  sha256: c5dc0a0f703836df15a31f304669865520717061e13b5dd74af384854b03ae7b

build:
  number: 0
  skip: True   # [py < 37]
  entry_points:
    - mikado = Mikado.__main__:main
    - daijin = Mikado.daijin.__main__:main
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - biopython >=1.78
    - dataclasses   # [ py < 37 ]
    - docutils
    - drmaa
    - hypothesis
    - marshmallow
    - marshmallow-dataclass
    - msgpack-python >=1.0.0
    - networkx >=2.3
    - numpy >=1.17.2
    - pandas >=1.0
    - pip
    - pyfaidx >=0.5.8
    - pysam >=0.15.3
    - pytest >=5.4.1
    - python
    - python-rapidjson >=1.0.0
    - pyyaml >=5.1.2
    - scipy >=1.3.1
    - snakemake >=5.7.0
    - sqlalchemy >=1.4.0
    - sqlalchemy-utils >=0.37
    - tabulate >=0.8.5
    - toml >=0.10.0
    - typeguard
  run:
    - biopython >=1.78
    - dataclasses   # [ py < 37 ]
    - docutils
    - drmaa
    - hypothesis
    - marshmallow
    - marshmallow-dataclass
    - msgpack-python >=1.0.0
    - networkx >=2.3
    - numpy >=1.17.2
    - pandas >=1.0
    - pip
    - pyfaidx >=0.5.8
    - pysam >=0.15.3
    - pytest >=5.4.1
    - python
    - python-rapidjson >=1.0.0
    - pyyaml >=5.1.2
    - scipy >=1.3.1
    - snakemake >=5.7.0
    - sqlalchemy >=1.4.0
    - sqlalchemy-utils >=0.37
    - tabulate >=0.8.5
    - toml >=0.10.0
    - typeguard

test:
  imports:
    - Mikado
    - Mikado.configuration
    - Mikado.loci
    - rapidjson
  commands:
    - mikado --help
    - daijin --help
    - python -c "import Mikado; Mikado.test(label='fast')"

about:
  home: https://github.com/EI-CoreBioinformatics/mikado
  summary: A Python3 annotation program to select the best gene model in each locus
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lucventurini
    - ljyanesm
    - gemygk
    - swarbred
