{% set name = "sonicparanoid" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sonicparanoid-{{ version }}.tar.gz
  sha256: e7ad4fba36c3017155b064845dd569889ef6af57790c4d6f6dd2ed1452a38bca

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-cache-dir -vvv 
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python >=3.7,<3.10
    - numpy
    - cython =0.29.33
    - pip
  run:
    - python >=3.7,<3.10

test:
  commands:
    - "sonicparanoid --help"

about:
  home: http://iwasakilab.k.u-tokyo.ac.jp/sonicparanoid
  summary: 'SonicParanoid: fast, easy and accurate orthology inference'
  dev_url: https://gitlab.com/salvo981/sonicparanoid2
  license: GPL-3.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - salvoc81 
    - WatanoK10
