# Project ID of SonicParanoid in git lab is 11148448

{% set name = "sonicparanoid" %}
{% set version = "2.0.0rc2" %}

# Working example of link that can be downloaded
# https://gitlab.com/api/v4/projects/11148448/repository/archive.zip?sha=6af30d9d7e7ebf40ca151ccbe2de56bdb1ccea8a

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://gitlab.com/salvo981/sonicparanoid2/-/archive/{{ version }}/sonicparanoid2-{{ version }}.tar.gz
  sha256: d2ebd2b687f91f081d9fc2ff4c494c1ed0dd95ba2893f1762465ffe2df1ed874


build:
  number: 0
  skip: True  # [py2k or py < 37 or py > 39]
  script: "{{ PYTHON }} -m pip install . --no-deps --no-cache-dir -vvv "

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python ==3.9
    - pip
    - setuptools >=57.4.0
    - wheel >=0.37.0
    - numpy >=1.21
        - cython
    - tqdm
    - gensim
    - mypy
    - smart-open
  run:
    - python ==3.9
    - pandas >=1.3.2
    - scipy >=1.7.1
    - biopython >=1.79
    - psutil >=5.8.0
    - scikit-learn >=0.24.2
    - filetype >=1.0.7
    - mmseqs2 >=13.45111
    - diamond >=2.0.12
    - blast >=2.12.0
    - mcl >=14.137

test:
  commands:
    - "sonicparanoid --help"

about:
  home: "http://iwasakilab.bs.s.u-tokyo.ac.jp/sonicparanoid/"
  license: "GNU General Public License v3"
  license_family: "GPL3"
  license_file: "LICENSE.md"
  summary: "SonicParanoid: fast, easy and accurate orthology inference"

extra:
  identifiers:
    - doi:10.1093/bioinformatics/bty631
