{% set name = "cython" %}
{% set version = "3.0.0a10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/96/02/ad03454f50d12ce889deb7cfdb1e5740829e89da5736cd01b785f2d275ea/Cython-3.0.0a10.tar.gz"
build:
  number: 0
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - Cython
    - Cython.Build
    - Cython.Build.Tests
    - Cython.Compiler
    - Cython.Compiler.Tests
    - Cython.Debugger
    - Cython.Debugger.Tests
    - Cython.Distutils
    - Cython.Plex
    - Cython.Runtime
    - Cython.Tempita
    - Cython.Tests
    - Cython.Utility
    - pyximport
  commands:
    - cython --help
    - cythonize --help
    - cygdb --help

about:
  home: "https://cython.org/"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "The Cython compiler for writing C extensions for the Python language."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
